 name: CI
 on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Descargar el código
         uses: actions/checkout@v5
       - name: Instalar .NET 10
         uses: actions/setup-dotnet@v5
         with:
          dotnet-version: '10.0.x'
       - name: Restaurar paquetes
         run: dotnet restore
       - name: Compilar
         run: dotnet build --no-restore -c Release
       - name: Ejecutar pruebas
         run: dotnet test --no-build -c Release
       - name: Construir imagen Docker
         run: docker build -t miprimeraapi .
